### ISSUE TITLE
Not building css

### ISSUE THREAD

**Issue by longseespace** [erickzhao/static-html-webpack-boilerplate#17]
**Describe the bug**
Running `npm run build` not bundling css (no `main.css` in `/dist`)

**To Reproduce**
1. `npm install`
2. `npm run build`

**Expected behavior**
- Transpiles SCSS
- Bundle into single `main.css`
- Included in `index.html`

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 71

Probably because of this PR: https://github.com/erickzhao/static-html-webpack-boilerplate/pull/15

**Comment by erickzhao** [comment]
Hey there, I'll try to give it a look tomorrow! 👍  thanks for reporting the issue.

**Comment by erickzhao** [comment]
Hey @longseespace, I looked it over and it seems that with the updated packages, the CSS is being now added inline into `app.bundle.js`.

<img width="997" alt="image" src="https://user-images.githubusercontent.com/16010076/51079005-5bed7800-168d-11e9-92f5-2ad12620d519.png">

Is that a big issue for you in production? The styles still get generated! I should probably update the README to reflect this fact.
