### ISSUE TITLE
upgrade to babel 7

### ISSUE THREAD

**Issue by ljmerza** [erickzhao/static-html-webpack-boilerplate#22]
**Is your feature request related to a problem? Please describe.**
update to babel 7

```bash
npm install -D babel-loader @babel/core @babel/preset-env
```

then in webpack.common

```
{
    test: /\.js$/,
    loader: 'babel-loader',
    options: {
        presets: ['@babel/preset-env']
    }
},
```

**Comment by Pommesloch** [comment]
You can also use https://github.com/babel/babel-upgrade for update

**Comment by erickzhao** [comment]
Thanks folks! Been a while since I've maintained this template, but I've ran the `npx` script to upgrade Babel. Seems to have gone smoothly.
