### ISSUE TITLE
How to use Bootstrap 4 ?

### ISSUE THREAD

**Issue by MacgyverMartins** [erickzhao/static-html-webpack-boilerplate#24]
Hi guys. I don't know if this is a feature request or just a simple question.
So, how to use Bootstrap 4 from NPM with this static boilerplate ?

Thks 😃

**Comment by erickzhao** [comment]
Hey @MacgyverMartins, apologies for the late response but I'd check out the Bootstrap docs for this: https://getbootstrap.com/docs/4.0/getting-started/webpack/
