### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by erickzhao** [erickzhao/static-html-webpack-boilerplate#8]
Right now, some of the dependencies in the repository are outdated. However, upgrading all of them to the latest version causes the live-reload from `webpack-dev-server` to stop working.

Need to comb through each package to figure out which one would cause a regression, pin it, and upgrade all others.

**Comment by erickzhao** [comment]
@ljmerza Thanks so much for looking into this! Would you like to take up this issue? 😄

**Comment by ljmerza** [comment]
I'm not sure if I'll be able to solve it. I was learning webpack from [here](https://survivejs.com/webpack/) and couldn't get it working for a static site. Then I stumbled on your repo which works on an older version of webpack. I can mess with it but still learning the internals.

**Comment by erickzhao** [comment]
@ljmerza No worries! I'll take a look on my end too. Worst case, I might just pin version numbers up.

**Comment by ljmerza** [comment]
ok using style-loader instead of MiniCssExtractPlugin makes CSS hot reloading work. I also got the html hot reloading to work. I think it's slow because we are not excluding node_modules in the watch dirs. I still had to comment out the js rule but I've updated the branch above to where I'm at.

**Comment by ljmerza** [comment]
ok I got everything working with the latest package versions. Could you test my branch on your end? I can squash merge if everything works out okay. 

https://github.com/ljmerza/static-html-webpack-boilerplate/tree/package-update

**Comment by erickzhao** [comment]
@ljmerza will find time this week to do so!

**Comment by erickzhao** [comment]
@ljmerza was more like 2 weeks than 1, but LGTM 👍, except that `npm run lint:js` is failing due to code formatting. If you open a PR and fix the small bug, I'll be happy to accept it!

**Comment by ljmerza** [comment]
ok fixed
